"""Small domain execution boundary for future direct Blender or MCP adapters."""
from pathlib import Path
from typing import Protocol

from .models import OrnamentSpec
from .qa import QAReport


class BlenderExecutor(Protocol):
    def initialize_scene(self, spec: OrnamentSpec) -> None: ...
    def save_checkpoint(self, path: Path) -> Path: ...
    def restore_checkpoint(self, path: Path) -> None: ...
    def render_validation_views(self, directory: Path) -> list[Path]: ...
    def export_placeholder_report(self, path: Path, report: QAReport) -> Path: ...
